version: '3'

services:
  tixfyi:
    build:
      context: .
      args:
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      dockerfile: Dockerfile
    container_name: tixfyi
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - .env
